### ISSUE TITLE
Please tell me this library LICENSE

### ISSUE THREAD

**Issue by osamingo** [blendle/zapdriver#10]
Hi, @JeanMertz.

I can't find license file.
Could you tell me this library license? (and please do commit LICENSE file!)

Best regards.

**Comment by JeanMertz** [comment]
Hi @osamingo, you are absolutely right, we should have added a license.

I've just added the license file, the project is licensed under the [ISC License](https://github.com/blendle/zapdriver/blob/master/LICENSE).

Have fun using the project!
