### ISSUE TITLE
timestamp format is incorrect

### ISSUE THREAD

**Issue by dhduvall** [blendle/zapdriver#15]
Stackdriver seems to be ignoring log entries with the `time` field encoded as an RF3339 string. I was able to get it to recognize the compound formats (separate `timestampSeconds` and `timestampNanos` fields, or a `timestamp` object with `seconds` and `nanos` fields) when appending to the log by hand, but I couldn't figure out how to get `zap` to encode a time as anything but a native type.

I did discover that `zapcore.EpochTimeEncoder` (floating point seconds since the epoch) works with the `time` field. I'll file a bug with Google to clarify (or correct?) the docs.

**Comment by JeanMertz** [comment]
Indeed, it looks like this was an oversight. The [README](https://github.com/blendle/zapdriver/blob/40161a31a07865be6ac4ade43edfa00161af4504/README.md) of this project states:

> It also sets some of the default keys to use the right names, such as `timestamp`, `severity`, and `message`.

Yet the code uses [`time`](https://github.com/blendle/zapdriver/blob/63327ce6a5a7d5cc97dbbeab5cdc771cfc62d1e2/encoder.go#L36).

Please feel free to send a PR to rename this field to `timestamp`, as described by the [Stackdriver documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity):

> A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds. Example: "2014-10-02T15:01:23.045123456Z".
