### ISSUE TITLE
Incompatibility with latest version of gcr.io/stackdriver-agents/stackdriver-logging-agent:0.7-1.6.1-1 ?

### ISSUE THREAD

**Issue by fproulx-dfuse** [blendle/zapdriver#16]
Hi,

2 days ago jsonPayload mapping for ZAP to StackDriver stopped working - we now get JSON as textPayload. 

It looks like that coincides with an auto-upgrade of master that updated the `fluentd-gcp` DaemonSet to `gcr.io/stackdriver-agents/stackdriver-logging-agent:0.7-1.6.1-1`

Are you aware of changes that might break zapdriver ?

**Comment by JeanMertz** [comment]
@fproulx-eoscanada we haven't updated our cluster yet, so I'm not sure what has changed. We still see properly JSON formatted messages in our logs, so it must indeed have something to do with the upgrade of the logging agent.

I suspect it could be related to one of these two release:

* https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/releases/tag/v0.7.0
* https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/releases/tag/v0.7.2

I'll dig into this when we upgrade our cluster and see the same issue, but that will take a couple of weeks. Let me know if you find anything in the mean time.

**Comment by fproulx-dfuse** [comment]
Google Support acknowledge a bug in their latest release.... they recommended to downgrade.
So the bug is not in zapdriver - sorry

**Comment by ernsheong** [comment]
I guess this is why all my INFO has become errors... thanks for the report.

![screenshot 2019-01-03 at 5 11 43 pm](https://user-images.githubusercontent.com/1343284/50630237-032a2b00-0f7b-11e9-8235-63bb05286ea0.png)
