### ISSUE TITLE
How to ensure SEVERITY info reflects correctly in the console?

### ISSUE THREAD

**Issue by ernsheong** [blendle/zapdriver#17]
I'm trying to achieve the following using Zapdriver with docker's `--log-driver=gcplogs` driver.

![image](https://user-images.githubusercontent.com/1343284/50372296-2f52bd00-0607-11e9-9b8e-bda96a11dc6f.png)

But I can only manage to get the severity information in `jsonPayload.data`:

![image](https://user-images.githubusercontent.com/1343284/50372311-7a6cd000-0607-11e9-8b64-eda6a5d7af0c.png)

How can I achieve this?

**Comment by JeanMertz** [comment]
The `severity` key should not be nested in the `data` object, but should be directly below `jsonPayload`. I'm not sure where the data object is coming from, it's not something that this library adds. Perhaps you accidentally added using Zap's `namespace` feature? If not, then I suppose `gcplogs` might be adding it.

Either way, the correct format can be found in the [Stackdriver documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry).

**Comment by ernsheong** [comment]
Thanks @JeanMertz, I believe it's up to `gcplogs` driver to implement this, but they are not going to for now: https://github.com/moby/moby/issues/22736

**Comment by JeanMertz** [comment]
Also, one more thing: I just realised from your screenshot above that the `data` key's value is actually a string, _not_ a JSON object, so I think the Docker log driver doesn't produce any structured logs, and this is something you will have to do yourself?

Anyway, good luck figuring this out, and if it does turn out to be an issue in this library, let me know, but I don't think it is.
