### ISSUE TITLE
include a minimal working example as quickstart guide

### ISSUE THREAD

**Issue by mark-kubacki** [blendle/zapdriver#20]
Hey, thanks for *zapdriver*!

I am struggling to fit it in my toy project, and feel that a minimal working example as quickstart guide could be of benefit here.

For example, going with the very last section of the current README file, this does not yield the promised *everything just works ™*:

```go
//name:above.go

package main

import (
        "fmt"

        "go.uber.org/zap"
        "go.uber.org/zap/zapcore"
        "github.com/blendle/zapdriver"
)

func main() {
        var log *zap.Logger
        {
                config := zap.NewDevelopmentConfig()
                config.EncoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder
                log, _ = config.Build(zapdriver.WrapCore()) // ←
                // log = log.Named("hello-world")
                defer log.Sync()
        }

        log.Info("stub start")
        fmt.Println("Hello world!")
        log.Info("stub end")
}
```
```console
$ export GOOGLE_APPLICATION_CREDENTIALS="….json"
$ go run above.go
```

… nothing shows up in *Stackdriver*,

**Comment by JeanMertz** [comment]
> this does not yield the promised _everything just works_

Fair point. We're using this library on top of GKE (Kubernetes), which already streams all the logs of all the containers to Stackdriver. This library only structures the logs in such away that they match the expected log format of Stackdriver. 

We use a small wrapper library around this library to make it easy to initialise the Zap logger itself. See: https://github.com/blendle/go-logger.

From looking at your snippet above, first of all, you _should_ see logs appear in stdout when you run `go run above.go`. The format of those log lines should match what Stackdriver expects. What you are missing is the component that sends those logs to the correct Stackdriver API. That is not something that this library provides, it is _only_ a wrapper around Zap to format the logs to Stackdriver's specification.

I'd welcome any updates to the README to link out to some helpful documentation on how to actually hook your application into Stackdriver, but I don't think actually writing those steps out in the README is within the scope of this library.
