### ISSUE TITLE
Labels aren't currently working as expected on GKE

### ISSUE THREAD

**Issue by JeanMertz** [blendle/zapdriver#4]
Even though this library has support for defining log [labels](https://github.com/blendle/zapdriver#label), this isn't actually properly parsed by Stackdriver at the moment. See [this PR](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/152) for more details.

If the outcome of that PR is that it won't be supported, I'll remove the code from this library, if it is, I'll change the key to the right one (probably `logging.googleapis.com/labels`).

Until then, I'll leave it as is.

**Comment by torbjornvatn** [comment]
It is now apparently https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/152#issuecomment-463347615
